version: "3"
services:
    database:
        image: postgres
        volumes:
            - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            POSTGRES_PASSWORD: example
        ports:
            - 5432:5432

    service_1:
        build: ./microservices/service_1
        volumes:
            - ./microservices/service_1:/app
        environment:
            - ASPNETCORE_URLS=http://+:5028
        ports:
            - 4000:5028
        depends_on:
            - database

    frontend:
        build: ./frontend
        volumes:
            - ./frontend:/app
        ports:
            - 3000:3000
