FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /app

COPY *.csproj ./
## Install all the dependencies
RUN dotnet restore 

COPY . ./
## Build the project , and publish the output to out folder
RUN dotnet publish -c Release -o out 

FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "watch", "--project", "service_1.csproj", "run"]